"""LegoTripod turning environment configuration for mjlab.

This task trains the lego-tripod (3-legged ball-joint robot) to spin in place.
It mirrors the MetaMachine `lego_tripod_turn.yaml` configuration:

  - Robot   : lego tripod XML generated by MetaMachine (3 motor joints)
  - Reward  : plateau_spin with target_spin=-3.0 (clockwise spin)
  - Obs     : projected_gravity + gyro of module-0 (6D) +
              dof_pos + dof_vel + last_action (9D) = 15D per step,
              history of 3 → 45D actor observation
  - Actions : 3 position targets, kp=8, kd=0.2, scale=1.0
  - Ctrl Hz : 20 Hz  (mj_dt=0.025s × decimation=2)
  - Episode : 1000 env steps  (50 s)
  - Term    : belly geom contacts the floor

Usage
-----
Register and train with::

    python mjlab/src/mjlab/scripts/train.py Mjlab-LegoTripod-Turn

Or import the cfg directly::

    from mjlab.tasks.lego_tripod import lego_tripod_turn_env_cfg
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path

import mujoco

from mjlab.actuator import CybergearPdActuatorCfg, IdealPdActuatorCfg, XmlMotorActuatorCfg
from mjlab.entity import EntityArticulationInfoCfg, EntityCfg
from mjlab.envs import ManagerBasedRlEnvCfg
from mjlab.envs import mdp as envs_mdp
from mjlab.envs.mdp.actions import JointEffortActionCfg, JointPositionActionCfg
from mjlab.managers.event_manager import EventTermCfg
from mjlab.managers.observation_manager import ObservationGroupCfg, ObservationTermCfg
from mjlab.managers.reward_manager import RewardTermCfg
from mjlab.managers.scene_entity_config import SceneEntityCfg
from mjlab.managers.termination_manager import TerminationTermCfg
from mjlab.scene import SceneCfg
from mjlab.sensor import ContactMatch, ContactSensorCfg
from mjlab.sim import MujocoCfg, SimulationCfg
from mjlab.terrains import TerrainEntityCfg
from mjlab.utils.noise import UniformNoiseCfg as Unoise
from mjlab.viewer import ViewerConfig

from .mdp import observations as mdp_obs
from .mdp import rewards as mdp_rew
from .mdp import terminations as mdp_term

# ---------------------------------------------------------------------------
# Robot XML path
# ---------------------------------------------------------------------------
# The robot XML is generated by MetaMachine.  Point to the fixed robot_debug.xml.
# You can regenerate it by running MetaMachine with render_mode='none' once.
_ROBOT_XML: Path = (
    Path(__file__).parent / "assets" / "lego_tripod.xml"
)


def _get_robot_spec() -> mujoco.MjSpec:
    """Load the lego-tripod MjSpec from the cached XML."""
    xml_path = _ROBOT_XML
    if not xml_path.exists():
        raise FileNotFoundError(
            f"LegoTripod robot XML not found at:\n  {xml_path}\n\n"
            "Run 'python metamachine_plugins/examples/train_lego_tripod_sb3.py "
            "--config metamachine_plugins/configs/lego_tripod_turn.yaml' once to "
            "generate the XML, then copy it to:\n  "
            f"{xml_path}"
        )
    spec = mujoco.MjSpec.from_file(str(xml_path))
    return spec


def _make_robot_entity_cfg() -> EntityCfg:
    """Build the EntityCfg for the lego-tripod robot.

    The robot XML already contains:
      - 3 hinge joints  (joint0, joint1, joint2)
      - 3 motor actuators (one per joint)
      - IMU sensors (imu_quat*, imu_gyro*, ...)

    We wrap the XML motors with IdealPdActuator to get position control at
    kp=8, kd=0.2, matching the MetaMachine config.
    """
    # Use Cybergear motor model with velocity-dependent torque limits.
    # MetaMachine applies the Cybergear T-N curve (tn_constraint=True):
    #   |vel| < 11.5 rad/s  → limit = 12.0 Nm
    #   |vel| ≥ 11.5 rad/s  → limit = max(0, -0.656·|vel| + 19.541)
    actuator_cfg = CybergearPdActuatorCfg(
        target_names_expr=("joint0", "joint1", "joint2"),
        stiffness=8.0,   # kp
        damping=0.2,     # kd
        # T-N curve params (Cybergear defaults match MetaMachine exactly)
        torque_max=12.0,
        vel_threshold=11.5,
        decay_slope=-0.656,
        decay_offset=19.541,
    )
    articulation_cfg = EntityArticulationInfoCfg(
        actuators=(actuator_cfg,),
        soft_joint_pos_limit_factor=1.0,
    )
    return EntityCfg(
        spec_fn=_get_robot_spec,
        articulation=articulation_cfg,
        init_state=EntityCfg.InitialStateCfg(
            pos=(0.0, 0.0, 0.35),
            # init_quat from the MetaMachine yaml: [0.135, -0.781, -0.417, 0.444]
            # MuJoCo / mjlab uses (w, x, y, z) ordering.
            rot=(0.135, -0.781, -0.417, 0.444),
            joint_pos={"joint0": 0.0, "joint1": 0.5, "joint2": -0.5},
            joint_vel={".*": 0.0},
        ),
    )


# ---------------------------------------------------------------------------
# Main factory function
# ---------------------------------------------------------------------------

def lego_tripod_turn_env_cfg(play: bool = False) -> ManagerBasedRlEnvCfg:
    """Create the LegoTripod-Turn training / play configuration."""

    robot_cfg = _make_robot_entity_cfg()

    # ------------------------------------------------------------------
    # Contact sensor: belly geom touching the floor  (termination)
    # ------------------------------------------------------------------
    belly_contact_cfg = ContactSensorCfg(
        name="belly_contact",
        primary=ContactMatch(
            mode="geom",
            pattern="robot/belly",
            entity=None,
        ),
        secondary=ContactMatch(mode="body", pattern="terrain"),
        fields=("found", "force"),
        reduce="netforce",
        num_slots=1,
    )

    # ------------------------------------------------------------------
    # Observations  (frame-major history, matching MetaMachine)
    # ------------------------------------------------------------------
    # MetaMachine constructs one 15D frame per step:
    #   [projected_gravity_m0(3), gyro_m0(3), dof_pos(3), dof_vel(3), last_action(3)]
    # then stores 3 frames in an ObservationBuffer in frame-major order:
    #   [frame_t-2(15D), frame_t-1(15D), frame_t-0(15D)]  → 45D
    #
    # To replicate this layout we use a **single** combined observation term
    # with history_length=3.  Per-component noise is specified via per-dim
    # tuples in UniformNoiseCfg so the standard enable_corruption works.
    #
    # Noise per component (from MetaMachine config):
    #   projected_gravity  dims [0:3]  → ±0.05
    #   gyro               dims [3:6]  → ±0.2
    #   dof_pos            dims [6:9]  → ±0.01
    #   dof_vel            dims [9:12] → ±1.5
    #   last_action        dims [12:15] → 0 (no noise)
    _noise_min = (
        -0.05, -0.05, -0.05,    # projected_gravity
        -0.2,  -0.2,  -0.2,     # gyro
        -0.01, -0.01, -0.01,    # dof_pos
        -1.5,  -1.5,  -1.5,     # dof_vel
         0.0,   0.0,   0.0,     # last_action (no noise)
    )
    _noise_max = (
         0.05,  0.05,  0.05,
         0.2,   0.2,   0.2,
         0.01,  0.01,  0.01,
         1.5,   1.5,   1.5,
         0.0,   0.0,   0.0,
    )

    actor_terms: dict[str, ObservationTermCfg] = {
        "obs_frame": ObservationTermCfg(
            func=mdp_obs.combined_frame_obs,
            params={
                "asset_cfg": SceneEntityCfg("robot"),
                "action_clip_min": -0.8,
                "action_clip_max": 0.8,
            },
            noise=Unoise(n_min=_noise_min, n_max=_noise_max),
            history_length=3,    # gives frame-major 45D
        ),
    }

    # Critic: same 15D frame (no noise, no history) + privileged info.
    critic_terms: dict[str, ObservationTermCfg] = {
        "obs_frame": ObservationTermCfg(
            func=mdp_obs.combined_frame_obs,
            params={
                "asset_cfg": SceneEntityCfg("robot"),
                "action_clip_min": -0.8,
                "action_clip_max": 0.8,
            },
        ),
        "base_ang_vel": ObservationTermCfg(
            func=envs_mdp.base_ang_vel,
        ),
        "base_lin_vel": ObservationTermCfg(
            func=envs_mdp.base_lin_vel,
        ),
    }

    observations = {
        "actor": ObservationGroupCfg(
            terms=actor_terms,
            concatenate_terms=True,
            enable_corruption=True,
            # NOTE: history_length is set per-term (on obs_frame), NOT group-level,
            # so the critic terms are unaffected.
        ),
        "critic": ObservationGroupCfg(
            terms=critic_terms,
            concatenate_terms=True,
            enable_corruption=False,
        ),
    }

    # ------------------------------------------------------------------
    # Actions: position control
    # ------------------------------------------------------------------
    # MetaMachine clips raw actions to [-0.8, 0.8] (symmetric_limit),
    # then adds default_dof_pos as offset.
    # scale=1.0, default_dof_pos=[0, 0.5, -0.5] used as offset.
    actions = {
        "joint_pos": JointPositionActionCfg(
            entity_name="robot",
            actuator_names=("joint0", "joint1", "joint2"),
            scale=1.0,
            use_default_offset=True,
            clip_raw=(-0.8, 0.8),  # MetaMachine symmetric_limit
        )
    }

    # ------------------------------------------------------------------
    # Events
    # ------------------------------------------------------------------
    events = {
        "reset_scene": EventTermCfg(
            func=envs_mdp.reset_scene_to_default,
            mode="reset",
        ),
        "reset_joints": EventTermCfg(
            func=envs_mdp.reset_joints_by_offset,
            mode="reset",
            params={
                # MetaMachine uses symmetric_limit=0.8 as joint noise range
                "position_range": (-0.8, 0.8),
                "velocity_range": (0.0, 0.0),
                "asset_cfg": SceneEntityCfg("robot", joint_names=("joint0", "joint1", "joint2")),
            },
        ),
    }

    # ------------------------------------------------------------------
    # Rewards
    # ------------------------------------------------------------------
    rewards = {
        "plateau_spin": RewardTermCfg(
            func=mdp_rew.plateau_spin,
            weight=1.0,
            params={
                "target_spin": -3.0,
                "asset_cfg": SceneEntityCfg("robot"),
            },
        ),
        "action_rate": RewardTermCfg(
            func=envs_mdp.action_rate_l2,
            weight=-0.01,
        ),
    }

    # ------------------------------------------------------------------
    # Terminations
    # ------------------------------------------------------------------
    # Episode length: 1000 steps × (0.025 s × 2) = 50 s
    terminations = {
        "time_out": TerminationTermCfg(func=envs_mdp.time_out, time_out=True),
        "belly_contact": TerminationTermCfg(
            func=mdp_term.belly_contact,
            params={"sensor_name": "belly_contact"},
        ),
    }

    # ------------------------------------------------------------------
    # Play-mode overrides
    # ------------------------------------------------------------------
    if play:
        terminations["time_out"] = TerminationTermCfg(
            func=envs_mdp.time_out,
            time_out=True,
            params={},
        )
        observations["actor"] = replace(
            observations["actor"], enable_corruption=False
        )

    # ------------------------------------------------------------------
    # Assemble
    # ------------------------------------------------------------------
    return ManagerBasedRlEnvCfg(
        scene=SceneCfg(
            terrain=TerrainEntityCfg(terrain_type="plane"),
            entities={"robot": robot_cfg},
            sensors=(belly_contact_cfg,),
            num_envs=1,
        ),
        observations=observations,
        actions=actions,
        events=events,
        rewards=rewards,
        terminations=terminations,
        viewer=ViewerConfig(
            origin_type=ViewerConfig.OriginType.ASSET_BODY,
            entity_name="robot",
            body_name="torso3",
            distance=1.5,
            elevation=-15.0,
            azimuth=90.0,
        ),
        sim=SimulationCfg(
            nconmax=100,
            njmax=500,
            mujoco=MujocoCfg(
                timestep=0.025,
                iterations=10,
                ls_iterations=20,
            ),
        ),
        # decimation=2 → control at 20 Hz  (0.025 × 2 = 0.05 s per env step)
        decimation=2,
        # 1000 env steps = 50 s
        episode_length_s=50.0,
    )
